# Generated by Django 3.1.2 on 2021-06-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=35)),
                ('gender', models.CharField(max_length=6)),
                ('company', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=30)),
                ('latitude', models.FloatField(blank=True, max_length=11, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=11, null=True)),
            ],
        ),
    ]
