# Generated by Django 2.2.5 on 2021-06-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=35)),
                ('gender', models.CharField(max_length=6)),
                ('company', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=30)),
                ('latitude', models.FloatField(max_length=11)),
                ('longitude', models.FloatField(max_length=11)),
            ],
        ),
    ]
